config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root :to => 'homes#top'
  get "/home/about" => "homes#about"
  resources :users, only:[:index, :show, :edit, :update]
  resources :books do
      resource :favorites, only: [:create, :destroy]
      resources :book_comments, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
  validates :title, presence: true, length: { maximum: 200 }
  validates :body, presence: true, length: { maximum: 200 }
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates_uniqueness_of :book_id, scope: :user_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  attachment :profile_image

  validates :name, length: { minimum: 2, maximum: 20 }
  validates :name, uniqueness: true
  validates :introduction, length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  def after_sign_in_path_for(resource)
      user_path(resource)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = book.id
    comment.save
    path = Rails.application.routes.recognize_path(request.referer)
    redirect_to path
  end

  def destroy
    BookComment.find_by(id: params[:id], book_id: params[:book_id]).destroy
    path = Rails.application.routes.recognize_path(request.referer)
    redirect_to path
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :authenticate_user!, except: [:top, :about]
  before_action :correct_user,   only: [:edit, :update, :destroy]


  def index
    @books = Book.all
    @book = Book.new
    @user = current_user
  end

  def show
    @book = Book.new
    @book_comment = BookComment.new
    @s_book = Book.find(params[:id])
    @user = @s_book.user
  end

  def create
    @user = current_user
    @books = Book.all
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] ="You have created book successfully."
      redirect_to book_path(@book.id)
    else
      render :index
    end
  end

  def edit
    #@user = User.find(params[:id])
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
       flash[:notice] ="You have updated book successfully."
    redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

 def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
 end


 private

  def correct_user
    @book = Book.find(params[:id])
    redirect_to(books_path) unless current_user?(@book.user)
  end

  def current_user?(user)
    user == current_user
  end

  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    path = Rails.application.routes.recognize_path(request.referer)
    redirect_to path
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    path = Rails.application.routes.recognize_path(request.referer)
    redirect_to path
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  # before_action :authenticate_user!, except: :top
  # before_action :correct_user,   only: [:edit, :update, :destroy]

  def top
  end

  def about
  end

  private

  def correct_user
    user = User.find(params[:id])
    redirect_to(user_path(current_user)) unless current_user?(user)
  end

  def current_user?(user)
    user == current_user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

before_action :authenticate_user!, except: [:top, :about]

  def index
    @book = Book.new
    @user = current_user
    @users = User.all
  end

  def show
    @sbook = Book.new
    @user = User.find(params[:id])
    @books = @user.books.reverse_order
  end

  def edit
    @user = User.find(params[:id])
    if @user.name != current_user.name
          redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] ="You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render 'users/edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_error_form.html.erb
<% if @book.errors.any? %>
  <div class = "alert" style = "color: red;">
    <h3>error</h3>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/books/edit.html.erb
<div class="row">
	  <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
		<h1>Editing Book</h1>
		<%= form_for @book do |f| %>
		<%= render 'error_form', model: f.object %>
			<div class="form-group">
				<%= f.label :Title %>
				<%= f.text_field :title, class: "form-control book_title" %>
			</div>

			<div class="form-group">
				<%= f.label :Opinion %>
				<%= f.text_area :body, class: "form-control book_title" %>
			</div>

			<div class="form-group">
				<%= f.submit "Update Book", class: "btn btn-success" %>
			</div>

		<% end %>
		<%= link_to "Show", book_path(@book) %>|
		<%= link_to "Back", books_path %>
	</div>
</div>

app/views/books/index.html.erb
<% if@book.errors.any? %>
          <div class="alert alert-warning">
            <ul>
              <% @book.errors.full_messages.each do |message| %>
              	<% logger.debug("-----------errors=#{message}") %>
              	<h2>error</h2>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
 <% end %>

<div class='container px-5 px-sm-0'>
<div class='row'>
	<div class='col-md-3'>
	<%= render "users/user_info", {user: @user, book: @book} %>

	<div class='col-md-8 offset-md-1'>
		<h2>Books</h2>
		<table class = 'table table-hover table-inverse'>
			<thead>
				<tr>
					<th></th>
					<th>Title</th>
					<th>Opinion</th>

				</tr>
			</thead>
			<tbody>
			<% Book.all.each do |book| %>
				<tr>
					<td><%= link_to user_path(book.user_id) do %>
						<%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", size:'40x40'%>
						<% end %>
					</td>
					<td><%= link_to book.title, book_path(book.id) %></td>
					<td><%= book.body %></td>
					<% if book.favorited_by?(current_user) %>
							<td>
								<%= link_to book_favorites_path(book), class: "fas fa-heart", :style=>"color:red;" , method: :delete do %>
	        			<%= book.favorites.count %>
	      				<% end %>
	      			</td>
    				<% else %>
    					<td>
      					<%= link_to book_favorites_path(book), class: "fas fa-heart", method: :post do %>
       						<%= book.favorites.count %>
      					<% end %>
      				</td>
  					<% end %>
					<td>
					  <%= "コメント数: #{book.book_comments.count}" %>
					</td>
				</tr>
			<% end %>
			</tbody>
		</table>
	</div>
  </div>
</div>
</div>

app/views/books/show.html.erb
<div class='container px-5 px-sm-0'>
<div class='row'>
	<div class='col-md-3'>
	<%= render "users/user_info", {user: @user, book: @book} %>

	<div class='col-md-8 offset-md-1'>
			<h2>Book detail</h2>
			<table class = "table">
					<tr>
						<td><a href="<%= user_path(@s_book.user)%>">
							<%= attachment_image_tag @s_book.user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", size:'40x40'%><br>
							<%= @s_book.user.name %>
						</a></td>
						<td>

						</td>
						<td><%= @s_book.title %></td>
						<td><%= @s_book.body %></td>
						<% if @user.id == current_user.id %>
							<td><%= link_to "Edit", edit_book_path(@s_book), class: "btn btn-success" %></td>
							<td><%= link_to "Destroy", book_path(@s_book), method: :delete, class: "btn btn-info", data: { confirm: 'Are you sure?' } %></td>
						<% end %>

						<% if @s_book.favorited_by?(current_user) %>
							<td>
								<%= link_to book_favorites_path(@s_book), class: "fas fa-heart", :style=>"color:red;" , method: :delete do %>
	        						<%= @s_book.favorites.count %>
	      						<% end %>
	      					</td>
    					<% else %>
    						<td>
      							<%= link_to book_favorites_path(@s_book), class: "fas fa-heart", method: :post do %>
       							<%= @s_book.favorites.count %>
      						<% end %>
      						</td>
  						<% end %>
							<td>
								  <%= "コメント数: #{@s_book.book_comments.count}" %>

							</td>
					</tr>

					<% @s_book.book_comments.each do |book_comment| %>
					<tr>
							<td>
									<a href="<%= user_path(book_comment.user)%>">
										<%= attachment_image_tag book_comment.user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", size:'40x40'%><br>
										<%= book_comment.user.name %>
									</a>
							</td>
							<td>
								<%= book_comment.comment %>
							</td>
							<td>
								<% if book_comment.user == current_user %>
									<td>
										<%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete, class: "btn btn-info", data: { confirm: 'Are you sure?' } %>
									</td>
								<% end %>
							</td>
					</tr>
					<% end %>
			</table>
						 <%= form_with(model:[@s_book, @book_comment], local:true)do |f| %>
						 	 <%= f.text_area :comment, value: nil %><br>
						 	 <%= f.submit '送信', :class=>"btn" %><br>
						 <% end %>
		</div>
	</div>
</div>
</div>

app/views/homes/about.html.erb
<div class='container'>
  <div class='row'>
    <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
  </div>
</div>

app/views/homes/top.html.erb
<div class="row">
    <div class='mx-auto col-11 col-sm-10 col-lg-8 col-xl-6'>
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
      <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
        </div>
        <div class="row">
          <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign Up</a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <script src="https://kit.fontawesome.com/23b02b2376.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
   <header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <a class="navbar-brand" href="/"><span>Bookers</span></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">
           <% if user_signed_in? %>
              <li><%= link_to "HOME", user_path(current_user.id), class: "fas fa-home nav-link text-light" %></li>
              <li><%= link_to "Users", users_path, class: "fas fa-users nav-link text-light"%></li>
              <li><%= link_to "Books", books_path, class: "fas fa-book-open nav-link text-light" %></li>
              <li><%= link_to "logout", destroy_user_session_path, method: :delete, class: "fas fa-sign-out-alt nav-link text-light" %></li>
            <% else %>
              <li><%= link_to "HOME", root_path, class: "fas fa-home nav-link text-light" %></li>
              <li><%= link_to "About", home_about_path, class: "fas fa-link nav-link text-light" %></li>
              <li><%= link_to "sign up", new_user_registration_path, class: "fas fa-user-plus nav-link text-light" %></li>
              <li><%= link_to "login", new_user_session_path, class: "fas fa-sign-in-alt nav-link text-light"%></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
</header>
    <main>
      <% if flash[:notice] %>
        <p style="color: #00ff00;"><%= flash[:notice] %></p>
      <% end %>
        <p id="notice"></p>
        <%= yield %>
    </main>
    <footer>
  <div class='container mt-5'>
  	<div class='row'>
    	<div class='mx-auto'>
    		<p>CopyRight Infratop.inc</p>
    	</div>
    </div>
  </div>
</footer>
  </body>
</html>

app/views/users/_error_form.html.erb
<% if @user.errors.any? %>
  <div class="alert" style = "color: red;">
    <h3><%= @user.errors.count %> errors prohibited this obj from being saved:</h3>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_user_info.html.erb
     <h2>User info</h2>
      <table class='table'>
			  <tr>
			  <%= attachment_image_tag user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "100x100" %>
			  </tr>
			  <tr>
				  <th>name</th>
				  <th><%= user.name %></th>
			  </tr>
			  <tr>
				  <th>introduction</th>
				  <th><%= user.introduction %></th>
			  </tr>
			</table>

			<div class='row'>
	         <p><%= link_to "Profile", edit_user_path(user), class: "btn btn-outline-secondary btn-block fas fa-user-cog" %></p>
			</div>

      <h2 class="mt-3">New book</h2>

     		 <%= form_with model:book, local:true do |f| %>

    	    <label for="book_title">Title</label>
    		  <div class="title">
    		      <%= f.text_field :title, value: nil, class: "col-xs-12 pull-right" %>
          </div>
		      <div class="form-group">
			      <label for="book_opinion">Opinion</label>
			        <div class="opinion">
			      	  <%= f.text_area :body, value: nil, class: "col-xs-12 pull-right" %><br>
			        </div>
			      	  <%= f.submit 'Create Book', :class=>"btn btn-success" %><br>
			     </div>
				<% end %>
    </div>

app/views/users/edit.html.erb
<div class='container'>
   <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
<h2>User info</h2>

<%= form_for (@user) do |f| %>
  <%= render 'error_form', {model: f.object} %>


  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name, autofocus: true %>
  </div>

    <div class="field">
    <%= f.label :profile_image_id %><br />
    <%= f.attachment_field :profile_image %>
  </div>

    <div class="field">
    <%= f.label :introduction %><br />
    <%= f.text_area :introduction %>
  </div>

  <div class="actions">
    <%= f.submit "Update User" %>
  </div>
<% end %>
</div>
</div>
</div>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
  	<div class='col-md-3'>
    	<%= render "users/user_info", {user: @user, book: @book} %>
      <div class='col-md-8 offset-md-1'>
        <h2>Users</h2>

        <table class="table table-striped col-xs-3">
          <thead>
            <tr>
              <th>image</th>
              <th>name</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <% @users.each do |user| %>
            <tr>
              <td>
                <%= attachment_image_tag user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "50x50" %>
              </td>
              <td>
                <%= user.name %>
              </td>
              <td><%= link_to "Show", user_path(user.id) %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
  </div>
</div>
</div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
 			<%= render "users/user_info", {user: @user, book: @sbook} %>
    	<div class='col-md-8 offset-md-1'>
      	<h2>Books</h2>

      <table class='table table-hover table-inverse'>
				  <thead>
				    <tr>
				      <th></th>
				      <th>Title</th>
				      <th>Opinion</th>
				      <th colspan="3"></th>
				    </tr>
				  </thead>

		  	<tbody>
 				<% @books.each do |book| %>
			  	<tr>
		        <td>
		        	<%= link_to user_path(@user) do %>
		 					<%= attachment_image_tag @user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "100x100" %>
		 					<% end %>
						</td>
		        <td>
		        	<%= link_to book_path(book.id) do %>
		   				<%= book.title %>
		    			<% end %>
		    		</td>
		        <td><%= book.body %></td>
		        <td>
				      <% if book.user == current_user %>
				      <%= link_to "Show", book_path(book) %>
				      <% end %>
				    </td>
    				<td>
				      <% if book.user == current_user %>
				      <%= link_to "Destroy", book_path(book), method: :delete, data: { confirm: 'Are you sure?' } %>
				      <% end %>
    				</td>
    							<% if book.favorited_by?(current_user) %>
							<td>
								<%= link_to book_favorites_path(book), class: "fas fa-heart", :style=>"color:red;" , method: :delete do %>
	        						<%= book.favorites.count %>
	      						<% end %>
	      					</td>
    					<% else %>
    						<td>
      							<%= link_to book_favorites_path(book), class: "fas fa-heart", method: :post do %>
       							<%= book.favorites.count %>
      						<% end %>
      						</td>
  						<% end %>
							<td>
					  		<%= "コメント数: #{book.book_comments.count}" %>
							</td>
	      	</tr>
	      	<% end %>
		 		</tbody>
			</table>
    </div>
  </div>
</div>
</div>